In [19]:
from twython import Twython
import json
import pandas as pd

# Load credentials from json file
with open("SeMA_twitter_credentials.json", "r") as file:
    lines = file.read()
    creds = json.loads(lines)

python_tweets = Twython(creds['CONSUMER_KEY'], creds['CONSUMER_SECRET'])

# Create our query
query = {'q': '#cedyacma2020',
        'count': 10,
        'lang': 'es',
        }

# Search tweets
dict_ = {'user': [], 'date': [], 'text': [], 'favorite_count': []}
for status in python_tweets.search(**query)['statuses']:
    dict_['user'].append(status['user']['screen_name'])
    dict_['date'].append(status['created_at'])
    dict_['text'].append(status['text'])
    dict_['favorite_count'].append(status['favorite_count'])

# Structure data in a pandas DataFrame for easier manipulation
df = pd.DataFrame(dict_)
df.sort_values(by='favorite_count', inplace=True, ascending=False)
df.head(10)

,date,favorite_count,text,user
4,Sat Jan 11 10:55:51 +0000 2020,6,La SeMA premiará con un diploma acreditativo y...,SeMA_matapl
8,Thu Jan 09 20:07:07 +0000 2020,6,Publicado el procedimiento para la solicitud d...,SeMA_matapl
5,Fri Jan 10 09:00:32 +0000 2020,1,Extendidos los plazos para minisimposios (31/0...,SeMA_matapl
0,Sat Jan 11 13:51:01 +0000 2020,0,RT @SeMA_matapl: Extendidos los plazos para mi...,pacoarandiga
1,Sat Jan 11 13:11:59 +0000 2020,0,RT @SeMA_matapl: La SeMA premiará con un diplo...,imus_us
2,Sat Jan 11 12:17:04 +0000 2020,0,RT @SeMA_matapl: La SeMA premiará con un diplo...,pacoarandiga
3,Sat Jan 11 11:24:58 +0000 2020,0,RT @SeMA_matapl: La SeMA premiará con un diplo...,NoeliaOrtegaa
6,Fri Jan 10 08:22:54 +0000 2020,0,RT @SeMA_matapl: Publicado el procedimiento pa...,pacoarandiga
7,Fri Jan 10 06:14:34 +0000 2020,0,RT @SeMA_matapl: Publicado el procedimiento pa...,imus_us